### ISSUE TITLE
Restart (or reload) services during bootstrap

### ISSUE THREAD

**Issue by mbarnes** [projectatomic/commissaire#88]
After correcting for https://github.com/projectatomic/commissaire/issues/87, on host machines that were previously failing I've had to bootstrap them **twice** to get them to pick up the new flannel configuration from etcd.

The bootstrap playbook has:
```
    - name: Enable and Start Services
      service:
        name: "{{ item }}"
        enabled: yes
        state: started
      with_items:
        - "{{ commissaire_flannel_service }}"
        - "{{ commissaire_docker_service }}"
        - "{{ commissaire_kubelet_service }}"
        - "{{ commissaire_kubeproxy_service }}"
```
But given that it just installed config files for these services and the services may already be running, don't we want `state: restarted` or at least `state: reloaded`?
